version: "3"

services:
  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # ports already used
    ports:
      - "54:53/tcp"
      - "54:53/udp"
      - "67:67/udp"
      - "82:80/tcp"
    environment:
      TZ: Europe/Amsterdam
      WEBPASSWORD: PASSWORD
      WEBTHEME: default-darker
    # Volumes store your data between container upgrades
    volumes:
      - "./etc-pihole/:/etc/pihole/"
      - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
    # Recommended but not required (DHCP needs NET_ADMIN)
    # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
